### ISSUE TITLE
Player Join Event Issue

### ISSUE THREAD

**Issue by tyduptyler13** [cybertiger/Bukkit-ScoreShare#1]
I found a bug in the plugin running on a spigot server.

This is 1.7.2 spigot and should be the same api as bukkit. Let me know if you think there is a easy solution to this.

> [18:49:17 ERROR]: Could not pass event PlayerJoinEvent to ScoreShare v1.2
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-1339]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1339]
>         at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1339]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1339]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.PlayerList.c(PlayerList.java:245) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.PlayerList.a(PlayerList.java:135) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.LoginListener.c(LoginListener.java:87) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.LoginListener.a(LoginListener.java:42) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:150) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [spigot.jar:git-Spigot-1339]
>         at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1339]
> Caused by: java.lang.IllegalArgumentException: The name 'serverStats_SIDEBAR' is longer than the limit of 16 characters
>         at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-1339]
>         at org.bukkit.craftbukkit.v1_7_R1.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:39) ~[spigot.jar:git-Spigot-1339]
>         at org.bukkit.craftbukkit.v1_7_R1.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:20) ~[spigot.jar:git-Spigot-1339]
>         at org.cyberiantiger.minecraft.scoreshare.ScoreShare$PlayerScoreboard.setDisplayObjectiveProvider(ScoreShare.java:483) ~[?:?]
>         at org.cyberiantiger.minecraft.scoreshare.ScoreShare.reset(ScoreShare.java:119) ~[?:?]
>         at org.cyberiantiger.minecraft.scoreshare.ScoreShare.onPlayerJoin(ScoreShare.java:308) ~[?:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot.jar:git-Spigot-1339]
>         ... 15 more

**Comment by tyduptyler13** [comment]
Closing this because its super old and I don't even remember anything about it. :p
